//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ups.OA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelFirstDBEntities : DbContext
    {
        public ModelFirstDBEntities()
            : base("name=ModelFirstDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customer { get; set; }
        public DbSet<OrderInfo> OrderInfo { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<R_Customer_RoleInfo> R_Customer_RoleInfo { get; set; }
        public DbSet<RoleInfo> RoleInfo { get; set; }
    }
}
